networks:
  primenet:
    external: true
services:
  pihole:
    image: pihole/pihole:latest
    secrets:
      - pihole_webpasswd
    restart: unless-stopped
    networks:
      primenet:
        ipv4_address: 192.168.1.253
    hostname: pi-hole
    environment:
      DNSMASQ_LISTENING: "all"
      ServerIP: "192.168.1.253"
      TZ: "America/New_York"
      WEBPASSWORD_FILE: pihole_webpasswd
    volumes:
      - /mnt/Main/AppData/pihole/etc-pihole:/etc/pihole
      - /mnt/Main/AppData/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1
      - 1.0.0.1
secrets:
  pihole_webpasswd:
    file: /mnt/Main/AppData/secrets/pihole_password.txt