version: "3.8"

services:
  pihole:
    image: pihole/pihole:latest
    secrets:
      - pihole_webpasswd
    restart: unless-stopped
    hostname: pi-hole
    environment:
      DNSMASQ_LISTENING: "all"
      ServerIP: "192.168.1.253"
      TZ: "America/New_York"
      WEBPASSWORD_FILE: pihole_webpasswd
    volumes:
      - /mnt/Main/AppData/pihole/etc-pihole:/etc/pihole
      - /mnt/Main/AppData/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    ports:
      - "192.168.1.253:53:53/udp"
      - "192.168.1.253:53:53/tcp"
      - "192.168.1.253:80:80/tcp"
      - "192.168.1.253:443:443/tcp"
    dns:
      - 1.1.1.1
      - 1.0.0.1
secrets:
  pihole_webpasswd:
    file: /mnt/Main/AppData/secrets/pihole_password.txt