services:
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pi-hole
    environment:
      TZ: "America/New_York"
      ServerIP: "192.168.1.253"
      DNSMASQ_LISTENING: "all"
      # read password from the Compose secret:
      WEBPASSWORD_FILE: pihole_webpasswd
    volumes:
      - /mnt/tank/apps/pi-hole:/etc/pihole
      - /mnt/tank/apps/pi-hole/dnsmasq.d:/etc/dnsmasq.d
    cap_add: [ "NET_ADMIN" ]
    ports:
      - "192.168.1.253:53:53/udp"
      - "192.168.1.253:53:53/tcp"
      - "192.168.1.253:80:80/tcp"
      - "192.168.1.253:443:443/tcp"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    secrets:
      - pihole_webpasswd

secrets:
  pihole_webpasswd:
    file: /mnt/tank/apps/secrets/pihole_password.txt
