version: "3.8"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    networks:
      dmznet:
        ipv4_address: 192.168.50.226
    environment:
      - TZ=America/New_York
      - PUID=3000
      - PGID=3000
      - VERSION=docker
      - PLEX_CLAIM=claim-goL3sgfGNHDA87PEMA5h
      - ADVERTISE_IP=http://192.168.50.226:32400/
    volumes:
      - /mnt/Main/AppData/plex:/config
      - /mnt/Main/Media:/data:ro
      - /mnt/Main/Media:/media:ro      # you added this for lowercase legacy
      - /mnt/Main/Media:/Media:ro      # <-- add this (capital M) to match the DB
      - /mnt/Main/AppData/plex/transcode:/transcode
      - /mnt/Main/AppData/plex/logs:/logs

networks:
  dmznet:
    external: true
